const SHORT_MOVIE = 40;

const WIDTH_SCREEN_DESKTOP = '1280';
const WIDTH_SCREEN_TABLET = '768';
const WIDTH_SCREEN_MOBILE = '320';

const QUANTITY_CARDS_DESKTOP = [12, 4];
const QUANTITY_CARDS_TABLET = [8, 2];
const QUANTITY_CARDS_MOBILE = [5, 2];

const BAD_REQUEST_ERROR = 400;
const CONFLICT_ERROR = 409;

const MOVIES_COUNTER_OBJ = {
  '1280': [12, 4],
  '768': [8, 2],
  '320': [5, 2],
};

export {
  MOVIES_COUNTER_OBJ,
  SHORT_MOVIE,
  WIDTH_SCREEN_DESKTOP,
  WIDTH_SCREEN_TABLET,
  WIDTH_SCREEN_MOBILE,
  QUANTITY_CARDS_DESKTOP,
  QUANTITY_CARDS_TABLET,
  QUANTITY_CARDS_MOBILE,
  BAD_REQUEST_ERROR,
  CONFLICT_ERROR,
}
